### ISSUE TITLE
vimiv won’t read hidden files

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [karlch/vimiv-qt#271] opened 2020-08-30 20:19 UTC
If running `vimiv .file.jpg`, `vimiv` will instead open the first non-hidden file of the directory. I couldn’t find a way to open my hidden image.

Why do I have hidden images, you ask me? They are `.face.ico` in my home folder. Also, that’s none of your business. ;)

**Comment by karlch** [comment] 2020-08-30 22:05
Thanks for the report!

The issue is that vimiv tries to be smart when opening a single image, i.e. it tries to open all image files in the current directory and focus the image opened. When `show_hidden` is set to `False` this fails when the only image passed is a hidden file as it will not be part of the generated filelist. I will think about how to solve this without breaking any existing functionality.

Temporary workarounds could be:
- Set `library.show_hidden` to `True` in the `vimiv.conf` to always show hidden files.
- Start vimiv via `vimiv -s library.show_hidden true .face.jpg` when opening a hidden file.
- Always pass a second file, although this is probably the most ridiculous option :laughing:

**Comment by karlch** [comment] 2020-10-10 10:48
This should have been fixed in 91bd06292bd86ff78a4bf47f6f8ee8f31b5852e4, sorry for the long delay. Let me know if there are further issues.

**Closed by karlch** 2020-10-10 10:48 UTC
Labels: bug
