### ISSUE TITLE
ModuleNotFoundError after upgrade to python 3.11

### ISSUE THREAD

**Issue by eyolf** [karlch/vimiv-qt#632] opened 2023-06-04 11:17 UTC
After the system-wide upgrade to python 3.11, I get the following when I try to open vimiv (qt-git version):

```
Traceback (most recent call last):
  File "/usr/bin/vimiv", line 7, in <module>
    from vimiv.startup import main
ModuleNotFoundError: No module named 'vimiv'
```

I'm on Arch, and the general upgrade happened on 4 May, and that's when the problems started to appear as well.

**Comment by jcjgraf** [comment] 2023-06-04 18:47
Thanks for reporting the issue. I am able to reproduce the error (by executing `make -f misc/Makefile DESTDIR=./installdir install`). It seems to be related to the setuptools packaging, or `setup.py` respectively. Though, with my limited python packaging knowledge I was not able to fix it.

I will ensure that @karlch will take notice of this issue.

**Comment by karlch** [comment] 2023-06-17 10:51
Sorry for the late reply, and thanks for reporting!

I am honestly not able to reproduce the issue. Have you tried re-installing the `vimiv-qt-git` package from the AUR to allow it to build in the python3.11 folders?

@jcjgraf
Installing vimiv with the Makefile globally (`sudo make install`) and to a local installdir, which is picked up by python, e.g. `make install DESTDIR=~/.local PREFIX=""` for me, work just fine. Not sure if `./installdir` is picked up by your python?
However, the uninstall command doesn't seem to work for custom `DESTDIR` and `PREFIXES`, I will open a new issue for this :blush:

**Comment by jcjgraf** [comment] 2023-06-17 11:20
@karlch Ah, your are right. The issue is indeed not the python version, but that `./installdir/XYZ` was not in the python path. Sorry for the noise 😬

**Comment by mcp292** [comment] 2023-06-26 18:13
Wouldn't the better practice be to make a `python-vimiv` package in the arch repo and have that install as a dependency?

**Comment by karlch** [comment] 2023-06-30 06:16
Could you explain why we would do that? Installing the `vimiv-qt-git` package works as intended, it just has to be rebuilt once a new python version comes out, like any other python dependent AUR package. I also don't see this split, or naming convention, happen elsewhere in the packages, e.g. in [qutebrowser-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qutebrowser-git).

**Comment by mcp292** [comment] 2023-06-30 16:25
I misunderstood the error message and the proposed solution. I interpreted the response to the error message was to install a pypi package named `vimiv` (`pip install vimiv`).

**Comment by Yutsuten** [comment] 2023-07-01 09:13
I was able to reproduce the issue (by accident). For me, the reason was that when I ran `makepkg -sic` to install the AUR package, my `pyenv`'s global python was set to `3.11.4`, not `system`. I didn't change the global python myself, so maybe it changed by itself?

Running `pyenv global system` (just to be sure I `git clean -xf` too) and reinstalling the package fixed the issue for me.

**Comment by karlch** [comment] 2023-07-02 14:40
So all in all seems like regular (python) packaging havoc - nothing vimiv specific - closing for now. In case there are vimiv-specific issues, happy to re-open of course.

**Closed by karlch** 2023-07-02 14:40 UTC

**Comment by mcp292** [comment] 2023-07-03 18:01
For the record, re-building cleared the error for me.
