### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by karlch** [karlch/vimiv-qt#47] opened 2019-03-24 08:57 UTC
Although this is not the main scope of vimiv, simple mouse support should be given. This includes:
* Binding mouse clicks to commands
* Binding scroll events to commands (same as click event?)

**Comment by OliverLew** [comment] 2019-11-13 13:47
Will mouse dragging also be considered? It's quite a easy way to pan images.

**Comment by karlch** [comment] 2019-11-13 16:53
Is panning the same as cropping an image? If so, this would be related to #8 and mouse dragging should certainly be supported by this widget. Probably using Qt internals.

I am not sure if a general way to bind to a mouse drag to commands would make any sense though.

**Comment by OliverLew** [comment] 2019-11-13 17:16
I was thinking about moving the image if it's zoomed in to be larger than the window size. The dragging is like what you can do in feh, sxiv and most mouse driven image viewer. Of course since it's kind of "mouse driven", I totally understand if you don't want to add this particular feature.

**Comment by karlch** [comment] 2019-11-13 17:56
Ah, now I see what you mean, thanks for the explanation! I never used this feature in other image viewers.

Currently at least scrolling with the mouse wheel is supported. My laptop trackpad can handle both dimensions simultaneously, so this is what I use to "pan" the image in case I don't want to use `hjkl`.

If the logic behind this is not too complicated, it can certainly be considered. As I would not use the feature myself, the priority is rather low, but any PR would certainly be accepted :)

Note for future self or any implementer:
In case we replace the `QScrollArea` in `gui.image` by [this](https://stackoverflow.com/questions/40683840/zooming-and-panning-an-image-in-a-qscrollarea), we may be able to solve panning and #20 in one shot.

**Comment by rifazn** [comment] 2019-11-15 16:38
Has the mouse wheel up and mouse wheel down event been implemented? If not, are they planned?

**Comment by karlch** [comment] 2019-11-15 19:13
In which sense? Currently they should scroll the image.

**Comment by rifazn** [comment] 2019-11-15 20:22
I wanted to bind something like `^wheel_up` and `^wheel_down` (Ctrl + Mouse Wheel up/down) for zooming in and out of the image respectively. I know the default binding for them is `+` and `-`, but being able to bind the mouse wheel would be really nice too.

**Comment by karlch** [comment] 2019-11-15 23:03
Certainly sounds like a good thing to have. I am currently working on an update of the image widget based on the initial panning input which should at least implement zooming with the mouse wheel and panning. Binding to custom commands may still be farther away, mainly as I do not know how to arbitrarily support *press ... release* cycles.

**Comment by OliverLew** [comment] 2019-12-02 07:59
@karlch I found a problem related to the latest commit about mouse support, so I guess it's OK to report here? :)
I found the zoom step with ctrl+wheel is too big in 0.4.1, directly from 23% to 800%. I did a little research and found the code here is zooming the image exponentially:
https://github.com/karlch/vimiv-qt/blob/37074e0754ddbf31e194017b0e71824d2983dbf2/vimiv/gui/image.py#L313
The problem is that according to [qt documentation](https://doc.qt.io/qt-5/qwheelevent.html#angleDelta), the angleDelta is normally 120 for most mouse wheel, making the zoom step `1.03^120=34.7`. Maybe dividing it by 120 will be much better :smile:

**Comment by karlch** [comment] 2019-12-02 10:24
That does sound like an issue, thanks for catching this. I only tested this with my touchpad which seems to have a finer resolution. I usually get steps between 0 to 10, depending on how fast I scroll. I will think about how to make the default sane for both cases.

**Comment by OliverLew** [comment] 2019-12-03 15:23
Yes, the scaling step is a lot finer now!

**Comment by karlch** [comment] 2019-12-03 22:48
Binding clicks and double clicks should now be possible but I have not added any default bindings as I don't have any in mind :thinking:. #136 is open for this.

I am no longer sure if binding drag/wheel to commands is useful in general. Dragging requires the start / end coordinate or a Qt interface which is not implemented by any command. The wheel passes a delta which is also not handled in general. I would therefore prefer to handle this on a per-suggestion basis much like the zooming with `<ctrl>wheel` and the panning was done. Suggestions are welcome and can be made by opening an issue, as usual.

Leaving this open for now as the new interface requires more testing and thinking, but I may close this soon :tm: if there are no objections.

**Comment by rifazn** [comment] 2019-12-05 12:43
Since zoom in and zoom out be done with `<ctrl>wheel` now, I won't mind at all if you close it.

**Closed** 2020-01-05 15:23 UTC
Labels: enhancement
